CREATE TABLE Products(
  Id INT AUTO_INCREMENT,
  Name VARCHAR(50) UNIQUE,
  Price INT NOT NULL DEFAULT 0,
  Currency VARCHAR(10) NOT NULL DEFAULT 'usd',
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (Id, Name)
);