CREATE TABLE Products(
  Id INT AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Price INT NOT NULL,
  Currency VARCHAR(10) DEFAULT 'usd',
  Updated DATETIME DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (Id)
);